### ISSUE TITLE
Cannot launch (non-technical person)

### ISSUE THREAD

**Issue by JohnnyBonk** [Cinnamon/kotaemon#135]
Hi, I followed the installation instructions but im not a software person. I tried to launch but it didn't open in browser. Here is the message I got:

Requirements are already installed

******************************************************
Setting up a local model
******************************************************

LOCAL_MODEL not set in the `.env` file.

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

Traceback (most recent call last):
  File "/Users/johnnybonk/Downloads/kotaemon-app/app.py", line 15, in <module>
    app = App()
  File "/Users/johnnybonk/Downloads/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/app.py", line 57, in __init__
    self.register_reasonings()
  File "/Users/johnnybonk/Downloads/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/app.py", line 83, in register_reasonings
    reasoning_cls = import_dotted_string(value, safe=False)
  File "/Users/johnnybonk/Downloads/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/utils/modules.py", line 47, in import_dotted_string
    return getattr(module, obj_name)
AttributeError: module 'ktem.reasoning.simple' has no attribute 'FullDecomposeQAPipeline'

Will exit now...

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by taprosoft** [comment]
Please see https://github.com/Cinnamon/kotaemon/issues/133 and wait for a few days for official non-tech users setup script

**Comment by yash-web3** [comment]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/kotaemon/app.py", line 13, in <module>
    from ktem.main import App  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/main.py", line 2, in <module>
    from ktem.app import BaseApp
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/app.py", line 8, in <module>
    from ktem.components import reasonings
  File "/workspaces/codespaces-blank/kotaemon/libs/ktem/ktem/components.py", line 11, in <module>
    from kotaemon.base import BaseComponent
ModuleNotFoundError: No module named 'kotaemon'
