### ISSUE TITLE
[BUG] - Can't start application

### ISSUE THREAD

**Issue by SamuXzX** [Cinnamon/kotaemon#159]
### Description

I followed the steps to install Kotaemon in Linux (simply running `bash run_linux.sh`), I asked to run the web interface after the installation and I even tried again launching the script, but the web interface doesn't open.

I add the output in the "logs" section.

### Reproduction steps

```bash
1. Install Kotaemon
2. Type 'Y' when asked for input to open the web interface
```

### Logs

```bash
samuele@thinkbook:~/Documenti/Programs/kotaemon-app/scripts$ bash run_linux.sh

******************************************************
Setting up Miniconda
******************************************************

Miniconda is installed at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/conda
Conda version: 
conda 24.7.1

******************************************************
Creating conda environment
******************************************************

Conda environment exists at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/env
Activate conda environment at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/env

******************************************************
Installing requirements
******************************************************

Requirements are already installed

******************************************************
Downloading and unzipping PDF.js
******************************************************

Destination directory /home/samuele/Documenti/Programs/kotaemon-app/libs/ktem/ktem/assets/prebuilt/pdfjs-4.0.379-dist already exists. Skipping download.

******************************************************
Setting up a local model
******************************************************

LOCAL_MODEL not set in the `.env` file.

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/samuele/Documenti/Programs/kotaemon-
[nltk_data]     app/install_dir/env/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
Traceback (most recent call last):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/manager.py", line 60, in build_index
    index.on_create()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/index.py", line 288, in on_create
    for key, value in self.get_admin_settings().items():
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/index.py", line 347, in get_admin_settings
    embedding_default = embedding_models_manager.get_default_name()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/embeddings/manager.py", line 112, in get_default_name
    raise ValueError("No models in pool")
ValueError: No models in pool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samuele/Documenti/Programs/kotaemon-app/app.py", line 15, in <module>
    app = App()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/app.py", line 68, in __init__
    self.initialize_indices()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/app.py", line 79, in initialize_indices
    self.index_manager.on_application_startup()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/manager.py", line 188, in on_application_startup
    self.build_index(**index)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/manager.py", line 68, in build_index
    raise ValueError(f'Cannot create index "{name}": {e}')
ValueError: Cannot create index "File": No models in pool

Will exit now...
```

### Browsers

Firefox

### OS

Linux

### Additional information

Firefox 129.0.2-1.fc40 has been installed from Fedora Linux.

**Comment by coopshea** [comment]
Same error here, MacOS, Brave Browser

**Comment by taprosoft** [comment]
Please check the new release that could fix this issue https://github.com/Cinnamon/kotaemon/releases/tag/v0.4.1.

**Comment by SamuXzX** [comment]
I run the update_linux.sh script but it didn't work. Then I deleted the old folder, downloaded the new release and launched run_linux.sh.
Now it successfully opens the browser, but I had to guess the password for the default user "admin".

Now I'm trying to set the OpenAI API key: I added it but I just see "Error" in the chat:
![immagine](https://github.com/user-attachments/assets/c4958fca-2d2e-4169-8dc7-168ba0c9b8af)

![immagine](https://github.com/user-attachments/assets/62e49eaa-4db8-44b7-89c8-6b7fa9ea980f)

I don't see any explanation in the user guide about what the default entries in the LLMs tab need: maybe replacing the placeholder with the API key is not enough.

**Comment by coopshea** [comment]
I'm on mac so this may be different, but I was able to get it to work. did you use the key including the "" or without?

**Comment by SamuXzX** [comment]
I tried in both ways. I suppose there's something missing in the OpenAI account? I created both an API Key and an assistant. I don't receive a description for the error, so I don't know what to do.

**Comment by taprosoft** [comment]
Can you give us some print out from the command line / console? Did it provide any helpful information to further debug this issue?

**Comment by coopshea** [comment]
I don't have the console logs anymore, but another issue i've had in the past with the api keys is accidentally including a space at the end. that took my a while to find...

**Comment by SamuXzX** [comment]
Looking at the output in the terminal it's pretty clear: I just don't have any quota...
```
samuele@thinkbook:~/Documenti/Programs/kotaemon-app/scripts$ bash run_linux.sh 

******************************************************
Setting up Miniconda
******************************************************

Miniconda is installed at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/conda
Conda version: 
conda 24.7.1

******************************************************
Creating conda environment
******************************************************

Conda environment exists at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/env
Activate conda environment at /home/samuele/Documenti/Programs/kotaemon-app/install_dir/env

******************************************************
Installing requirements
******************************************************

Requirements are already installed

******************************************************
Downloading and unzipping PDF.js
******************************************************

Destination directory /home/samuele/Documenti/Programs/kotaemon-app/libs/ktem/ktem/assets/prebuilt/pdfjs-4.0.379-dist already exists. Skipping download.

******************************************************
Setting up a local model
******************************************************

Local model not found: llama3.1:8b

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/samuele/Documenti/Programs/kotaemon-
[nltk_data]     app/install_dir/env/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
User "admin" already exists
Failed to fetch document from https://raw.githubusercontent.com/Cinnamon/kotaemon/vlocal/docs/about.md: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/Cinnamon/kotaemon/vlocal/docs/about.md
Failed to fetch document from https://raw.githubusercontent.com/Cinnamon/kotaemon/vlocal/docs/usage.md: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/Cinnamon/kotaemon/vlocal/docs/usage.md
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
len(results)=0, len(file_list)=1
len(results)=0, len(file_list)=1
User-id: 1, can see public conversations: True
Session reasoning type None
Session LLM None
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7fc6c5a60100>, FSPath=PosixPath('/home/samuele/Documenti/Programs/kotaemon-app/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7fc6c5a2d1b0>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fc6c2d142b0>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fc6c2d16f80>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fc6c2d141f0>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7fc714594220>, FSPath=<theflow.base.unset_ object at 0x7fc714594220>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7fc714594220>, VS=<theflow.base.unset_ object at 0x7fc714594220>, file_ids=[], user_id=<theflow.base.unset_ object at 0x7fc714594220>)]
searching in doc_ids []
Got 0 retrieved documents
len (original) 0
Got 0 images
Trying LLM streaming
Traceback (most recent call last):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 804, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/reasoning/simple.py", line 677, in stream
    answer = yield from self.answering_pipeline.stream(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/reasoning/simple.py", line 379, in stream
    for out_msg in self.llm.stream(messages):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/kotaemon/llms/chats/openai.py", line 225, in stream
    resp = self.openai_response(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/kotaemon/llms/chats/openai.py", line 313, in openai_response
    return client.chat.completions.create(**params)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1026, in _request
    return self._retry_request(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1026, in _request
    return self._retry_request(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1075, in _retry_request
    return self._request(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

It was so obvious, I'm sorry. Do you suggest any form of free LLM access just to try Kotaemon?

**Comment by cin-albert** [comment]
@SamuXzX You can use Kotaemon with [Groq API](https://console.groq.com/docs/models). It offers many free and fast LLMs.
Just create an API key and add it to Kotaemon UI as follows:

**Specification:**
```bash
api_key: <your_groq_api_key>
base_url: https://api.groq.com/openai/v1
model: llama3-8b-8192
```

![image](https://github.com/user-attachments/assets/4e507d26-888a-441e-b356-8286b6f3b249)

**Comment by SamuXzX** [comment]
Thank you!

Unfortunately it seems I still receive an authentication error:

```
Session reasoning type None
Session LLM None
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7fa012425240>, FSPath=PosixPath('/home/samuele/Documenti/Programs/kotaemon-app/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7fa012424d30>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa010ec8280>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa010eca050>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa010e04d90>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7fa061094220>, FSPath=<theflow.base.unset_ object at 0x7fa061094220>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7fa061094220>, VS=<theflow.base.unset_ object at 0x7fa061094220>, file_ids=[], user_id=<theflow.base.unset_ object at 0x7fa061094220>)]
searching in doc_ids ['50a9455f-9752-4c6d-b0ef-73af2943320d']
retrieval_kwargs: dict_keys(['do_extend', 'scope', 'filters'])
Traceback (most recent call last):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/pages/chat/__init__.py", line 804, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/reasoning/simple.py", line 660, in stream
    docs, infos = self.retrieve(message, history)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/reasoning/simple.py", line 488, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/ktem/index/file/pipelines.py", line 162, in run
    docs = self.vector_retrieval(text=text, top_k=self.top_k, **retrieval_kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/kotaemon/indices/vectorindex.py", line 188, in run
    emb = self.embedding(text)[0].embedding
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1675, in __call__
    return self._create_callable(getattr(self.ff_original_obj, "__call__"))(
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1663, in wrapper
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1661, in wrapper
    output = callable_obj(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/kotaemon/embeddings/base.py", line 10, in run
    return self.invoke(text, *args, **kwargs)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/kotaemon/embeddings/openai.py", line 104, in invoke
    resp = self.openai_response(client, input=input_, **kwargs).dict()
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/samuele/Documenti/Programs/kotaemon-app/install_dir/env/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fa010d262c0 state=finished raised AuthenticationError>]
```

**Comment by mmcc007** [comment]
I get the same `AuthenticationError`. When running locally it works fine. When I deploy to a AWS EC2, I get the `AuthenticationError` when I associate a file or files with the chat.

**Comment by mmcc007** [comment]
> I get the same `AuthenticationError`. When running locally it works fine. When I deploy to a AWS EC2, I get the `AuthenticationError` when I associate a file or files with the chat.


Since I'm only using cohere.com it was fixed by making it the default for LLM and embedding. (I think it prompts for that in the local install, but not on the remote install for whatever reason)
