### ISSUE TITLE
[BUG] - Can't lauch after installation

### ISSUE THREAD

**Issue by linuaries** [Cinnamon/kotaemon#187]
### Description

Tried 
1) with/without Docker at ubuntu20.04(wsl) - failed
2) run_windows.bat at Windows 10 - failed

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
(kotaemon) root@ZD-PC:/home/aistudio/RAG/kotaemon# python app.py
Traceback (most recent call last):
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aistudio/RAG/kotaemon/app.py", line 15, in <module>
    app = App()
  File "/home/aistudio/RAG/kotaemon/libs/ktem/ktem/app.py", line 42, in __init__
    self._theme = gr.Theme.from_hub("lone17/kotaemon")
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/themes/base.py", line 187, in from_hub
    space_info = api.space_info(name)
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2520, in space_info
    data = r.json()
  File "/root/miniconda3/envs/kotaemon/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by pimooook** [comment]
Same as you

**Comment by HugoWang232608** [comment]
Same problem

**Comment by cin-albert** [comment]
@linuaries It looks like Gradio failed to download the [theme](lone17/kotaemon). Is there any issue with your internet connection, e.g. firewall blocking Gradio connection?

**Comment by linuaries** [comment]
> @linuaries It looks like Gradio failed to download the [theme](lone17/kotaemon). Is there any issue with your internet connection, e.g. firewall blocking Gradio connection?

It seems Huggingface.co is blocked in China. But export HF_ENDPOINT="https://hf-mirror.com" also can't solve this problem.

**Comment by linuaries** [comment]
This start issue could be solved by eidt self._theme of libs/ktem/ktem/app.py:
```python
        try:
            self._theme = gr.Theme.from_hub("lone17/kotaemon")
        except Exception as e:
            print(f"Error loading theme:{e}")
            self._theme = gr.Theme(primary_hue="blue",
                                   secondary_hue="gray") # Fallback to default theme
```

Thanks for "社恐患者杨老师" from webchat group

**Comment by sticktoFE** [comment]
> > @linuaries It looks like Gradio failed to download the [theme](lone17/kotaemon). Is there any issue with your internet connection, e.g. firewall blocking Gradio connection?
> 
> It seems Huggingface.co is blocked in China. But export HF_ENDPOINT="https://hf-mirror.com" also can't solve this problem.

docker run .....-e https_proxy=ip:port ....    try a local ip like 192.168.0.100, not 127.0.0.1 not localhost
