### ISSUE TITLE
[BUG] - <title>requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by shnulailai** [Cinnamon/kotaemon#216]
### Description

Hi:
    Thank you for your great work,but when I start this project,I meet some problems,how to do?Thinks to help.

Traceback (most recent call last):
  File "/mnt/workspace/lailai/RAG/kotaemon/app.py", line 15, in <module>
    app = App()
  File "/mnt/workspace/lailai/RAG/kotaemon/libs/ktem/ktem/app.py", line 42, in __init__
    self._theme = gr.Theme.from_hub("lone17/kotaemon")
  File "/mnt/workspace/lailai/env/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/themes/base.py", line 187, in from_hub
    space_info = api.space_info(name)
  File "/mnt/workspace/lailai/env/anaconda3/envs/kotaemon/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/workspace/lailai/env/anaconda3/envs/kotaemon/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2520, in space_info
    data = r.json()
  File "/mnt/workspace/lailai/env/anaconda3/envs/kotaemon/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by pzc163** [comment]
same error

**Comment by taprosoft** [comment]
This is to be some random HuggingFace Hub down time. Please check this issue from Gradio https://github.com/gradio-app/gradio/issues/1450

You can try to set `GRADIO_ANALYTICS_ENABLED=false` to see if this fixes the issue. Or, just wait for some time and launch the app again.

**Comment by mayulu** [comment]
Same error, after tried:
```
$GRADIO_ANALYTICS_ENABLED=false python app.py
```

Also same error.
Host envirement: conda, python3.10, macOS
