### ISSUE TITLE
[BUG] - Error while uploadng file for GraphRag-UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 0: character maps to <undefined>      

### ISSUE THREAD

**Issue by mohdyasa** [Cinnamon/kotaemon#217]
### Description

Traceback (most recent call last):
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\_main_.py", line 68, in <module>
    index_cli(
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 92, in index_cli
    pipeline_config: str | PipelineConfig = config or _create_default_config(
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 222, in _create_default_config
    parameters = _read_config_parameters(root, reporter)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 248, in _read_config_parameters
    reporter.success(f"Reading settings from {settings_yaml}")
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\progress\rich.py", line 135, in success    
    self._console.print(f"🚀 [green]{message}[/green]")
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 1683, in print
    with self:
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 864, in _exit_
    self._exit_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 0: character maps to <undefined>      
len(results)=1, len(file_list)=1

### Reproduction steps

```bash
1. Go to GraphFile Upload
2. Upload a file 
3. File upload success but graph relationship creation fails
4. Always get below error-
Traceback (most recent call last):
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\_main_.py", line 68, in <module>
    index_cli(
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 92, in index_cli
    pipeline_config: str | PipelineConfig = config or _create_default_config(
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 222, in _create_default_config
    parameters = _read_config_parameters(root, reporter)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\cli.py", line 248, in _read_config_parameters
    reporter.success(f"Reading settings from {settings_yaml}")
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\graphrag\index\progress\rich.py", line 135, in success    
    self._console.print(f"🚀 [green]{message}[/green]")
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 1683, in print
    with self:
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 864, in _exit_
    self._exit_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\devPC\anaconda3\envs\kotaemon\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 0: character maps to <undefined>      
len(results)=1, len(file_list)=1
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by mohdyasa** [comment]
Error: 'charmap' codec can't encode character '\u2714' in position 111: character maps to <undefined>
