### ISSUE TITLE
[BUG] - <Error> tenacity.RetryError: RetryError[<Future at 0x7feaa7ef2980 state=finished raised AuthenticationError>]

### ISSUE THREAD

**Issue by phamkhactu** [Cinnamon/kotaemon#227]
### Description

Upload file successfully index -> select ```Search In File(s) ``` and choose file uploaded, then ask question, get error
![image](https://github.com/user-attachments/assets/ca3da562-5398-4885-a598-525b4c52af9c)

### Reproduction steps

```bash
1. click upload file
2. select file uploaded
3. chat
```

### Logs

```bash
Session reasoning type None
Session LLM None
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7feac0c83f40>, FSPath=PosixPath('/home/tupk/tupk/llm/langchain_tools/kotaemon/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7feac0ca1330>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7feab410fe20>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7feab40b4670>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7feab40b4340>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7feb763c9ff0>, FSPath=<theflow.base.unset_ object at 0x7feb763c9ff0>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7feb763c9ff0>, VS=<theflow.base.unset_ object at 0x7feb763c9ff0>, file_ids=[], user_id=<theflow.base.unset_ object at 0x7feb763c9ff0>)]
searching in doc_ids ['03d48f57-4605-401d-a33c-253e471268fc']
retrieval_kwargs: dict_keys(['do_extend', 'scope', 'filters'])
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 804, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 660, in stream
    docs, infos = self.retrieve(message, history)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 488, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/ktem/ktem/index/file/pipelines.py", line 162, in run
    docs = self.vector_retrieval(text=text, top_k=self.top_k, **retrieval_kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/kotaemon/kotaemon/indices/vectorindex.py", line 188, in run
    emb = self.embedding(text)[0].embedding
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1675, in __call__
    return self._create_callable(getattr(self.ff_original_obj, "__call__"))(
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1663, in wrapper
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1661, in wrapper
    output = callable_obj(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1261, in exec
    return child(*args, **kwargs, __fl_runstates__=__fl_runstates__)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/kotaemon/kotaemon/embeddings/base.py", line 10, in run
    return self.invoke(text, *args, **kwargs)
  File "/home/tupk/tupk/llm/langchain_tools/kotaemon/libs/kotaemon/kotaemon/embeddings/openai.py", line 104, in invoke
    resp = self.openai_response(client, input=input_, **kwargs).dict()
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/tupk/anaconda3/envs/llm/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7feaa7ef2980 state=finished raised AuthenticationError>]
```

### Browsers

Chrome

### OS

Linux

**Comment by shresthakamal** [comment]
You need to change the index embedding to the one you have specified as.

**Comment by phv2312** [comment]
Thank @shresthakamal , we have made the doc, you can check it out @phamkhactu  https://github.com/Cinnamon/kotaemon/blob/main/docs/local_model.md#use-local-models-for-rag
