### ISSUE TITLE
[BUG] - Lanuch error after installation on Windows

### ISSUE THREAD

**Issue by Carkham** [Cinnamon/kotaemon#231]
### Description

Thank you very much for such a great tool, I have some difficulties installing and using it on Windows. After running the `run_windows.bat` and successfully installing the required dependencies, it fails to start with the following error.

<img width="865" alt="image" src="https://github.com/user-attachments/assets/46b782ad-1b78-4fa3-8c11-a0604deb75ec">

### Reproduction steps

```bash
1. Go to 'scripts/'
2. Click on 'run_windows.bat'
3. See error
```

### Logs

```bash
I tried running the run_windows.bat multiple times after the first boot failure, so what is provided here is the error log for subsequent runs.

=================================================================

******************************************************
Setting up Miniconda
******************************************************

Conda is installed at D:\pythonpro\kotaemon-app\install_dir\conda
Conda version:
conda 24.7.1

******************************************************
Creating conda environment
******************************************************

Conda environment exists at D:\pythonpro\kotaemon-app\install_dir\env
Activate conda environment at D:\pythonpro\kotaemon-app\install_dir\env

******************************************************
Installing Kotaemon
******************************************************

Dependencies are already installed

******************************************************
Setting up a local model
******************************************************

Local model not found: llama3.1:8b

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

[nltk_data] Downloading package punkt_tab to D:\pythonpro\kotaemon-
[nltk_data]     app\install_dir\env\lib\site-
[nltk_data]     packages\llama_index\core\_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
GraphRAG dependencies not installed. GraphRAG retriever pipeline will not work properly.
User "admin" already exists
Setting up quick upload event
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\dependencies\utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\pythonpro\kotaemon-app\install_dir\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

### Browsers

Microsoft Edge

### OS

Windows

**Comment by taprosoft** [comment]
@Carkham this is due to a updated Python package that conflict with our setup script. Please use the latest version and run the setup again.
