### ISSUE TITLE
[BUG] - Unable to start app after installing langchain-google-genai

### ISSUE THREAD

**Issue by jaredpek** [Cinnamon/kotaemon#246]
### Description

Error when trying to start the app after installing langchain-google-genai

### Reproduction steps

```bash
1. pip install langchain-google-genai
2. python app.py
```

### Error Trace

```
Traceback (most recent call last):
  File "C:\Coding\Projects\kotaemon\app.py", line 13, in <module>
    from ktem.main import App  # noqa
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\main.py", line 3, in <module>
    from ktem.pages.chat import ChatPage
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\pages\chat\__init__.py", line 14, in <module>
    from ktem.reasoning.prompt_optimization.suggest_conversation_name import (
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\reasoning\prompt_optimization\__init__.py", line 1, in <module>
    from .decompose_question import DecomposeQuestionPipeline
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\reasoning\prompt_optimization\decompose_question.py", line 3, in <module>
    from ktem.llms.manager import llms
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\llms\manager.py", line 220, in <module>
    llms = LLMManager()
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\llms\manager.py", line 36, in __init__
    self.load()
  File "C:\Coding\Projects\kotaemon\libs\ktem\ktem\llms\manager.py", line 47, in load
    self._models[item.name] = deserialize(item.spec, safe=False)
  File "C:\Coding\Projects\kotaemon\venv\lib\site-packages\theflow\utils\modules.py", line 168, in deserialize
    return cls(**params)
  File "C:\Coding\Projects\kotaemon\libs\kotaemon\kotaemon\llms\chats\langchain_based.py", line 258, in __init__
    super().__init__(
  File "C:\Coding\Projects\kotaemon\libs\kotaemon\kotaemon\llms\chats\langchain_based.py", line 23, in __init__
    self._obj = self._lc_class(**params)
  File "C:\Coding\Projects\kotaemon\venv\lib\site-packages\langchain_core\load\serializable.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Coding\Projects\kotaemon\venv\lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "C:\Coding\Projects\kotaemon\venv\lib\site-packages\pydantic\v1\main.py", line 1100, in validate_model
    values = validator(cls_, values)
  File "C:\Coding\Projects\kotaemon\venv\lib\site-packages\langchain_google_genai\chat_models.py", line 864, in validate_environment
    if not values["model"].startswith("models/"):
KeyError: 'model'
```

### Browsers

Google Chrome

### OS

Windows 11

**Comment by jaredpek** [comment]
had to prefix the model_name with "model/"
