### ISSUE TITLE
[BUG] - <title>No module named 'theflow

### ISSUE THREAD

**Issue by wangyc23** [Cinnamon/kotaemon#248]
### Description

finished the install process, but can not launching in browser

### Reproduction steps

```bash
******************************************************
Setting up a local model
******************************************************

Local model not found: llama3.1:8b

******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

Traceback (most recent call last):
  File "/Users/nothing/resource/kotaemon-app/app.py", line 3, in <module>
    from theflow.settings import settings as flowsettings
ModuleNotFoundError: No module named 'theflow'

Will exit now...
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
******************************************************
Launching Kotaemon in your browser, please wait...
******************************************************

Traceback (most recent call last):
  File "/Users/nothing/resource/kotaemon-app/app.py", line 3, in <module>
    from theflow.settings import settings as flowsettings
ModuleNotFoundError: No module named 'theflow'

Will exit now...
```

### Browsers

Safari

### OS

MacOS

**Comment by cristianohello** [comment]
why???

**Comment by wangyc23** [comment]
> why???

I tried it several times, this bug didn't appear again. Sorry to say that I'm confusing about it too.

**Comment by lfpvillegas** [comment]
This is still happening on a fresh windows install. I have already commented it in  in #430 

```
Starting Kotaemon UI... (prebuilt PDF.js is at C:\kotaemon-app\libs\ktem\ktem\assets\prebuilt\pdfjs-4.0.379-dist)
Traceback (most recent call last):
  File "C:\kotaemon-app\app.py", line 3, in <module>
    from theflow.settings import settings as flowsettings
ModuleNotFoundError: No module named 'theflow'
```

Please reopen it.

**Comment by EthanLiBin** [comment]
It might be due to the global Python environment. Execute `which python` to check if it is the same as the Python used by `conda create`.
