### ISSUE TITLE
[BUG] - <title>Connection failed. Got error: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

### ISSUE THREAD

**Issue by BorampetBhavani** [Cinnamon/kotaemon#280]
### Description

Even though I changed the model name from gpt-4 to gpt-4o still I am getting the same error and when I ask any question ,its showing error.Even if I use olama I am getting connection error.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Trying LLM streaming
Traceback (most recent call last):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 973, in _request
    response = self._client.send(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_client.py", line 926, in send
    response = self._send_handling_auth(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "C:\Temp\kotaemon-app\install_dir\env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\gradio\utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\ktem\pages\chat\__init__.py", line 804, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\ktem\reasoning\simple.py", line 677, in stream
    answer = yield from self.answering_pipeline.stream(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\ktem\reasoning\simple.py", line 379, in stream
    for out_msg in self.llm.stream(messages):
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\kotaemon\llms\chats\openai.py", line 225, in stream
    resp = self.openai_response(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\kotaemon\llms\chats\openai.py", line 313, in openai_response
    return client.chat.completions.create(**params)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\resources\chat\completions.py", line 679, in create
    return self._post(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 997, in _request
    return self._retry_request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 1075, in _retry_request
    return self._request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 997, in _request
    return self._retry_request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 1075, in _retry_request
    return self._request(
  File "C:\Temp\kotaemon-app\install_dir\env\lib\site-packages\openai\_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

### Browsers

Chrome

### OS

Windows

**Comment by phv2312** [comment]
Hmm. It seems that this problem related to the OpenAI API and not related to this repo.
Can you first:
- Check all the credentials (from OpenAI) again to ensure you have enough privileges to call API successfully?
