### ISSUE TITLE
[BUG] - OCR is not running

### ISSUE THREAD

**Issue by lastsign** [Cinnamon/kotaemon#307]
### Description

Hi everyone, I'm wondering why is not running on the server and not unavailable by `DEFAULT_OCR_ENDPOINT = "http://127.0.0.1:8000/v2/ai/infer/"`

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ptycho/kotaemon/libs/kotaemon/tests/test_table_reader.py", line 56, in <module>
    ocr_reader(fullocr_output())
  File "/home/ptycho/kotaemon/libs/kotaemon/tests/test_table_reader.py", line 34, in ocr_reader
    documents = reader.load_data(input_file)# , response_content=fullocr_output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/kotaemon/libs/kotaemon/kotaemon/loaders/ocr_loader.py", line 83, in load_data
    resp = tenacious_api_post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/kotaemon/libs/kotaemon/kotaemon/loaders/ocr_loader.py", line 30, in tenacious_api_post
    resp = requests.post(url=url, files=files, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/.cache/pypoetry/virtualenvs/kotaemon-sDjngYLQ-py3.11/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/.cache/pypoetry/virtualenvs/kotaemon-sDjngYLQ-py3.11/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/.cache/pypoetry/virtualenvs/kotaemon-sDjngYLQ-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/.cache/pypoetry/virtualenvs/kotaemon-sDjngYLQ-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptycho/.cache/pypoetry/virtualenvs/kotaemon-sDjngYLQ-py3.11/lib/python3.11/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### OS

Linux

**Comment by phv2312** [comment]
Hi, the OCR loader is not working because it requires the 3rd service to run on beforehand.
Recently, we have pushed the new PR which integrate the GOT-OCR 2.0 for image reader. 
Can you try it out ? [PR](https://github.com/Cinnamon/kotaemon/pull/355)

**Comment by lastsign** [comment]
> Hi, the OCR loader is not working because it requires the 3rd service to run on beforehand. Recently, we have pushed the new PR which integrate the GOT-OCR 2.0 for image reader. Can you try it out ? [PR](https://github.com/Cinnamon/kotaemon/pull/355)

Hi, no i didn't.
I mean this app install dependencies for Tesseract. I was thinking It should work local without 3rd service to run.

I've tried implement via tesseract but without 'strong table oriented'.
So that works for me.

 I'll check it out [PR](https://github.com/Cinnamon/kotaemon/pull/355), thanks

**Comment by heapsoftware** [comment]
Need OCR for PDFs working as well, when I upload a PDF which is created by a scanner that scans in pages, it puts the scanned pages into a multi-page PDF. Need to be able to upload the PDF, which then it does an OCR to extract the text and use that extracted text for reasoning.
