### ISSUE TITLE
[BUG] - <GraphRAG can't run>

### ISSUE THREAD

**Issue by KosmoCHE** [Cinnamon/kotaemon#309]
### Description

While I have successfully completed the GraphRAG Collection ,I still can't chat with the support of GraphRAG.
The error message in terminal is showed below:
```
Session reasoning type None
Session LLM None
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7f9faa12ece0>, FSPath=PosixPath('/Users/sience/Desktop/kotaemon/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7f9fa9f36860>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9faca0e890>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9faca0e860>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9f8ed195a0>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7f9fb30b13f0>, FSPath=<theflow.base.unset_ object at 0x7f9fb30b13f0>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7f9fb30b13f0>, VS=<theflow.base.unset_ object at 0x7f9fb30b13f0>, file_ids=['7deb5e7b-9c4c-44a2-be89-8261fb5c30c7'], user_id=<theflow.base.unset_ object at 0x7f9fb30b13f0>)]
searching in doc_ids []
[2024-09-19T06:19:11Z WARN  lance::dataset] No existing dataset at /Users/sience/Desktop/kotaemon/ktem_app_data/user_data/files/graphrag/596b3a81-a35e-4c9b-813d-342750b0a946/output/20240919-141738/artifacts/lancedb/entity_description_embeddings.lance, it will be created
Entity count: 30
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/Users/sience/Desktop/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 704, in message_selected
    return retrieval_history[index], plot_history[index]
IndexError: list index out of range
```
I can promise that the GraphRAG Collection has completed successfully .
![graphragsuccess](https://github.com/user-attachments/assets/21d5b807-441c-42f8-b3cf-bd5f6d4e63b9)

I have good reason to suspect that this highlighted parameter is wrong in the terminal error message mentioned earlier

> Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7f9faa12ece0>, **FSPath=PosixPath('/Users/sience/Desktop/kotaemon/ktem_app_data/user_data/files/index_1')**,

### Reproduction steps

```bash
Follow the official tutorial steps
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
User-id: 1, can see public conversations: True
Session reasoning type None
Session LLM None
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7f9faa12ece0>, FSPath=PosixPath('/Users/sience/Desktop/kotaemon/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7f9fa9f36860>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9faca0e890>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9faca0e860>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f9f8ed195a0>), mmr=False, rerankers=[CohereReranking(cohere_api_key='', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7f9fb30b13f0>, FSPath=<theflow.base.unset_ object at 0x7f9fb30b13f0>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7f9fb30b13f0>, VS=<theflow.base.unset_ object at 0x7f9fb30b13f0>, file_ids=['7deb5e7b-9c4c-44a2-be89-8261fb5c30c7'], user_id=<theflow.base.unset_ object at 0x7f9fb30b13f0>)]
searching in doc_ids []
[2024-09-19T06:19:11Z WARN  lance::dataset] No existing dataset at /Users/sience/Desktop/kotaemon/ktem_app_data/user_data/files/graphrag/596b3a81-a35e-4c9b-813d-342750b0a946/output/20240919-141738/artifacts/lancedb/entity_description_embeddings.lance, it will be created
Entity count: 30
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/Users/sience/Desktop/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 704, in message_selected
    return retrieval_history[index], plot_history[index]
IndexError: list index out of range
```

**Comment by adoresever** [comment]
You can use ubuntu or mas.try it!

**Comment by Pedestrian-yu** [comment]
I use Mac OS,I will try ubuntu or win recently

**Comment by KosmoCHE** [comment]
> You can use ubuntu or mas.try it!

I use Mac OS.AndI will try ubuntu or win recently

**Comment by taprosoft** [comment]
Please check the new release.
