### ISSUE TITLE
[BUG] HTTPS Certificate error with Milvus

### ISSUE THREAD

**Issue by micuentadecasa** [Cinnamon/kotaemon#385]
### Description

I´m using the docker version of the app. I'm trying to use Milvus vectorstore with a Milvus server, but I´m getting an error with the certificate, as it is managed by llamaindex I don´t know how to handle it. I have tested some solutions but didn´t worked, I put the workarounds below in additional info. 
I can do openssl connection to the server from the docker image command line, but from the application it fails.

### Reproduction steps

```bash
1. add credentials to milvus.py (it is hardcoded)
2. change flowsettings.py to select milvus vector store
3. build the docker image and run it
4. upload a document
5. do a query. the engine find the documents store items, but it fails to connect to the milvus vector store.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
E0000 00:00:1728626237.175788      46 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626237.622169      37 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626238.624582      43 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626239.619308      46 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626240.211203      40 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626242.912061      46 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1728626243.161213      37 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
Failed to create new connection using: dbee0f3151a6441f9e0ebd763e0ec459
Exception in thread Thread-4 (<lambda>):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/libs/ktem/ktem/index/file/pipelines.py", line 399, in <lambda>
    target=lambda: list(insert_chunks_to_vectorstore())
  File "/app/libs/ktem/ktem/index/file/pipelines.py", line 387, in insert_chunks_to_vectorstore
    self.handle_chunks_vectorstore(chunks, file_id)
  File "/app/libs/ktem/ktem/index/file/pipelines.py", line 429, in handle_chunks_vectorstore
    self.vector_indexing.add_to_vectorstore(chunks)
  File "/app/libs/kotaemon/kotaemon/indices/vectorindex.py", line 94, in add_to_vectorstore
    self.vector_store.add(
  File "/app/libs/kotaemon/kotaemon/storages/vectorstores/milvus.py", line 85, in add
    self._lazy_init(dim)
  File "/app/libs/kotaemon/kotaemon/storages/vectorstores/milvus.py", line 59, in _lazy_init
    super().__init__(
  File "/app/libs/kotaemon/kotaemon/storages/vectorstores/base.py", line 94, in __init__
    self._client = LIClass(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/llama_index/vector_stores/milvus/base.py", line 263, in __init__
    self._milvusclient = MilvusClient(
  File "/usr/local/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/usr/local/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/usr/local/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on xxxx.es:443, illegal connection params or server unavailable)>
E0000 00:00:1728626246.475364      44 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
Failed to create new connection using: feab452209a14d589c344f5fa7af289e
Exception in thread Thread-9 (query_vectorstore):
```

### Additional information

I did next workarounds (didn´t worked):

1. add the certificate that is giving problems to the CA CERT in the docker image
# install certificates
# Copy the certificate from your Windows machine into the container
# Replace "path/to/your/certificate.crt" with the correct path on your system
# Install required packages (ca-certificates) for SSL/TLS
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy the custom certificate to the appropriate directory
COPY xxx.pem /usr/local/share/ca-certificates/xxxx.crt

# Run the command to update the CA certificates
RUN update-ca-certificates

# Set the REQUESTS_CA_BUNDLE environment variable globally
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

2. add ssl config to milvus.py
 # Add SSL options to bypass SSL verification or point to CA certificates
        # Assuming that llama_index's MilvusVectorStore supports these kwargs
        ssl_config={"enabled": True,  "root_certificate": "/etc/ssl/certs/ca-certificates.crt"}

    super().__init__(
                uri=uri,
                token=self._token,
                collection_name=self._collection_name,
                dim=dim,
                **self._kwargs,
                **ssl_config,
            )

**Comment by micuentadecasa** [comment]
At the end I solved the issue doing a port forwarding with OC command line because the Milvus server is in an OpenShift server, I couldn't solve the issue with the certificate.
