### ISSUE TITLE
[BUG] GraphRAG create_base_entity_graph error

### ISSUE THREAD

**Issue by tonydavis629** [Cinnamon/kotaemon#393]
### Description

When indexing a document with GraphRAG, it fails with error 
`create_base_entity_graph❌ Errors occurred during the pipeline run, see logs for more details.`

When trying to chat with this document, I get the following error:
```
2024-10-14 22:03:34 Session LLM None
2024-10-14 22:03:34 Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
2024-10-14 22:03:34 Reasoning state {'app': {'regen': False}, 'pipeline': {}}
2024-10-14 22:03:34 Thinking ...
2024-10-14 22:03:34 Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7f98ebd6a950>, FSPath=PosixPath('/app/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7f98ebf6f940>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f98ebce86d0>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f98ebcebfa0>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7f98ebceb040>), mmr=False, rerankers=[CohereReranking(cohere_api_key='<COHERE_API_KEY>', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7f999a5aff70>, FSPath=<theflow.base.unset_ object at 0x7f999a5aff70>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7f999a5aff70>, VS=<theflow.base.unset_ object at 0x7f999a5aff70>, file_ids=['de3ee653-5b64-4f0a-a2d4-a0bad380d7f4'], user_id=<theflow.base.unset_ object at 0x7f999a5aff70>)]
2024-10-14 22:03:34 searching in doc_ids []
2024-10-14 22:03:34 Traceback (most recent call last):
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
2024-10-14 22:03:34     response = await route_utils.call_process_api(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
2024-10-14 22:03:34     output = await app.get_blocks().process_api(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
2024-10-14 22:03:34     result = await self.call_function(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
2024-10-14 22:03:34     prediction = await utils.async_iteration(iterator)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
2024-10-14 22:03:34     return await iterator.__anext__()
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
2024-10-14 22:03:34     return await anyio.to_thread.run_sync(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-10-14 22:03:34     return await get_async_backend().run_sync_in_worker_thread(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024-10-14 22:03:34     return await future
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024-10-14 22:03:34     result = context.run(func, *args)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
2024-10-14 22:03:34     return next(iterator)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
2024-10-14 22:03:34     response = next(iterator)
2024-10-14 22:03:34   File "/app/libs/ktem/ktem/pages/chat/__init__.py", line 876, in chat_fn
2024-10-14 22:03:34     for response in pipeline.stream(chat_input, conversation_id, chat_history):
2024-10-14 22:03:34   File "/app/libs/ktem/ktem/reasoning/simple.py", line 655, in stream
2024-10-14 22:03:34     docs, infos = self.retrieve(message, history)
2024-10-14 22:03:34   File "/app/libs/ktem/ktem/reasoning/simple.py", line 483, in retrieve
2024-10-14 22:03:34     retriever_docs = retriever_node(text=query)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
2024-10-14 22:03:34     raise e from None
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
2024-10-14 22:03:34     output = self.fl.exec(func, args, kwargs)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
2024-10-14 22:03:34     return run(*args, **kwargs)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
2024-10-14 22:03:34     raise e from None
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
2024-10-14 22:03:34     _output = self.next_call(*args, **kwargs)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
2024-10-14 22:03:34     return self.next_call(*args, **kwargs)
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
2024-10-14 22:03:34     return self.run(*args, **kwargs)
2024-10-14 22:03:34   File "/app/libs/ktem/ktem/index/file/graph/pipelines.py", line 345, in run
2024-10-14 22:03:34     context_builder = self._build_graph_search()
2024-10-14 22:03:34   File "/app/libs/ktem/ktem/index/file/graph/pipelines.py", line 204, in _build_graph_search
2024-10-14 22:03:34     entity_df = pd.read_parquet(f"{INPUT_DIR}/{ENTITY_TABLE}.parquet")
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 667, in read_parquet
2024-10-14 22:03:34     return impl.read(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 267, in read
2024-10-14 22:03:34     path_or_handle, handles, filesystem = _get_path_or_handle(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
2024-10-14 22:03:34     handles = get_handle(
2024-10-14 22:03:34   File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 882, in get_handle
2024-10-14 22:03:34     handle = open(handle, ioargs.mode)
2024-10-14 22:03:34 FileNotFoundError: [Errno 2] No such file or directory: '/app/ktem_app_data/user_data/files/graphrag/254a1fc4-cf98-4487-a101-0385439521ae/output/create_final_nodes.parquet'
```

### Reproduction steps

```bash
1. Go to 'Files'
2. Click on 'GraphRAG collection'
3. Index a PDF
4. See error
```

### Browsers

Chrome, Brave

### OS

Linux

**Comment by taprosoft** [comment]
@tonydavis629 please check if you are using latest version, seem to be an old issue.

**Comment by tonydavis629** [comment]
It is indeed the latest version

**Comment by taprosoft** [comment]
@tonydavis629 if possible, could you use the Docker installation method to see if this issue persists?

**Comment by joeiren** [comment]
same error.
I'm using docker :main-full :latest version .
addition log output: 

[2024-10-15T03:34:01Z WARN  lance::dataset] No existing dataset at /app/ktem_app_data/user_data/docstore/index_2.lance, it will be created
indexing step took 0.24047589302062988
Initializing project at /app/ktem_app_data/user_data/files/graphrag/704476dc-1f64-44a1-b508-9e5b4d329ac8

/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

**Comment by taprosoft** [comment]
@joeiren 
seem you haven't set the API key for GraphRAG 
https://github.com/Cinnamon/kotaemon#setup-graphrag
Please follow this guide.

**Comment by tonydavis629** [comment]
@taprosoft I have tried this using both the docker full and lite builds. The normal retriever works fine. I have also set the GRAPHRAG_API_KEY env var in the .env file. I still get the same error as @joeiren

**Comment by rlabs-oss** [comment]
if settings are changed is a complete re-install needed? (delete ktem_app_data and the install_dir) then scripts/linux_run.sh again? - would be good to show what configurations files are in use during the startup.

**Comment by joeiren** [comment]
I've set GRAPHRAG_API_KEY in the .env file and it's not work
![image](https://github.com/user-attachments/assets/adb0ba07-0d9b-42f2-8aef-e2f6b2a7aad8)

**Comment by taprosoft** [comment]
@tonydavis629 @joeiren 
to use with Docker, please use this launch command 
```
docker run \
-e GRAPHRAG_API_KEY=<YOUR_OPENAI_KEY> \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-e GRADIO_SERVER_PORT=7860 \
-p 7860:7860 -it --rm \
ghcr.io/cinnamon/kotaemon:main-full
```

If you are launching from the command line on Linux and MacOS, use
`GRAPHRAG_API_KEY=<YOUR_OPENAI_KEY> python app.py`

**Comment by tonydavis629** [comment]
Ah, that works. Fantastic! Thank you so much. I think maybe the dockerfile should load .env variables?

**Comment by taprosoft** [comment]
@tonydavis629 no .env file will only be used in non-docker installation

**Comment by tonydavis629** [comment]
I see, I was confused at the `COPY .env.example /app/.env` dockerfile line. Thanks for the help, closing.

**Comment by sunnf8888** [comment]
我也有相同的的错误,0.7.1 的版本

**Comment by davidlee8086** [comment]
@taprosoft Could `GRAPHRAG_API_KEY` use Azure OpenAI?

**Comment by taprosoft** [comment]
@davidlee8086 you have to set `USE_CUSTOMIZED_GRAPHRAG_SETTING=true` and modify sample setting file to support Azure OpenAI https://github.com/Cinnamon/kotaemon/blob/main/settings.yaml.example

Use something like: 

```
docker run \
-e USE_CUSTOMIZED_GRAPHRAG_SETTING=true \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-e GRADIO_SERVER_PORT=7860 \
-v /path/to/local/setting.yaml.example:/app/settings.yaml.example \
-p 7860:7860 -it --rm \
ghcr.io/cinnamon/kotaemon:main-full
```

**Comment by suramcs** [comment]
@taprosoft , I am struggling to make graphrag work using custom settings with Azure OpenAI. Request you to provide detailed steps on the same. I am using latest Docker image on Ubuntu 24.04.
Also, would it make sense to have configuration similar to LLM and Embedding for graphrag? To me it seems very intuitive than changing a configuration file. Thank you very much for this great tool.

Following is the log

Page numbers: 144
Got 144 page thumbnails
Adding documents to doc store
indexing step took 0.7822182178497314
Initializing project at /app/ktem_app_data/user_data/files/graphrag/cfd14a68-75a4-4608-87b5-c7a2c5de2a79

/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: index__2__group

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/app/libs/ktem/ktem/index/file/ui.py", line 1353, in load_files
    results = session.execute(statement).all()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: index__2__group
[SQL: SELECT index__2__group.id, index__2__group.date_created, index__2__group.name, index__2__group.user, index__2__group.data 
FROM index__2__group]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by taprosoft** [comment]
@suramcs 

> Also, would it make sense to have configuration similar to LLM and Embedding for graphrag? To me it seems very intuitive than changing a configuration file.

You can checkout installation from source and use the experimental` nano-graphrag` implementation. This will help to directly use default LLM & embedding models in Kotaemon for GraphRAG.
https://github.com/Cinnamon/kotaemon#setup-graphrag

If you want to stick to original MS GraphRAG, I think tweaking `setting.yaml.example` is the only thing we can do here to make it support Azure OpenAI. Check out official documentation for more detail. https://microsoft.github.io/graphrag/config/env_vars/
