### ISSUE TITLE
[BUG] When using RAG to upload files and when indexing with GraphRAG, an error will be reported, but there is a file in the local user_data.

### ISSUE THREAD

**Issue by zzll22** [Cinnamon/kotaemon#400]
### Description

Traceback (most recent call last):
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/ktem/ktem/index/file/pipelines.py", line 784, in stream
    file_id, docs = yield from pipeline.stream(
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/ktem/ktem/index/file/pipelines.py", line 633, in stream
    yield from self.handle_docs(docs, file_id, file_name)
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/ktem/ktem/index/file/pipelines.py", line 375, in handle_docs
    self.handle_chunks_docstore(chunks, file_id)
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/ktem/ktem/index/file/pipelines.py", line 411, in handle_chunks_docstore
    self.vector_indexing.add_to_docstore(chunks)
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/kotaemon/kotaemon/indices/vectorindex.py", line 86, in add_to_docstore
    self.doc_store.add(docs)
  File "/Users/zhaolong/Desktop/TS_Platform/kotaemon-main/libs/kotaemon/kotaemon/storages/docstores/lancedb.py", line 53, in add
    document_collection.add(data)
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lancedb/table.py", line 1301, in add
    self.schema,
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lancedb/table.py", line 973, in schema
    return self._dataset.schema
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lancedb/table.py", line 955, in _dataset
    return self._ref.dataset
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lancedb/table.py", line 836, in dataset
    self._dataset = lance.dataset(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lance/__init__.py", line 89, in dataset
    ds = LanceDataset(
  File "/opt/anaconda3/envs/kotaemon/lib/python3.10/site-packages/lance/dataset.py", line 168, in __init__
    self._ds = _Dataset(
ValueError: Dataset at path Users/zhaolong/Desktop/TS_Platform/kotaemon-main/ktem_app_data/user_data/docstore/index_1.lance was not found: Not found: Users/zhaolong/Desktop/TS_Platform/kotaemon-main/ktem_app_data/user_data/docstore/index_1.lance/_versions/1.manifest, /Users/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:140:23, /Users/runner/work/lance/lance/rust/lance/src/dataset/builder.rs:310:35

When using RAG to upload files and when indexing with GraphRAG, an error will be reported, but there is a file in the local user_data. I don’t know how to solve it.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by taprosoft** [comment]
Please make sure that you provided a key for GraphRAG and setup correctly as mentioned here https://github.com/Cinnamon/kotaemon?tab=readme-ov-file#setup-graphrag
