### ISSUE TITLE
[BUG] Error during Chat using Doubao API

### ISSUE THREAD

**Issue by EvelynBai** [Cinnamon/kotaemon#424]
### Description

Hi, I'm using the Doubao API for GraphRAG construction and embedding. The graph construction step worked smoothly, but I'm encountering an issue when trying to interact via the chat box—it displays an "error" message.

The logs indicate an "Unauthorized" error during chatting QA, even though I've updated the .env and settings.yaml files correctly (I'll paste them below for reference). The initial connection tests were successful, and the graph construction also completed without any problems. 

### My configuration files are attached: 
.env:
`USE_CUSTOMIZED_GRAPHRAG_SETTING=true

OPENAI_API_BASE=https://api.openai.com/v1
OPENAI_API_KEY=<MY_OPENAI_API_KEY>
OPENAI_CHAT_MODEL=gpt-4o-mini-2024-07-18
OPENAI_EMBEDDINGS_MODEL=text-embedding-3-small

AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_API_KEY=
OPENAI_API_VERSION=2024-02-15-preview
AZURE_OPENAI_CHAT_DEPLOYMENT=gpt-4o-mini-2024-07-18
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=text-embedding-3-small

COHERE_API_KEY=<COHERE_API_KEY>

LOCAL_MODEL=llama3:latest
LOCAL_MODEL_EMBEDDINGS=nomic-embed-text:latest

GRAPHRAG_API_KEY=<MY_DOUBAO_API_KEY>
GRAPHRAG_LLM_MODEL=ep-20241023141551-9gkxh
GRAPHRAG_EMBEDDING_MODEL=ep-20241023145958-t97rc
GRAPHRAG_LLM_REQUEST_TIMEOUT=1800.0

AZURE_DI_ENDPOINT=
AZURE_DI_CREDENTIAL=

PDF_SERVICES_CLIENT_ID=
PDF_SERVICES_CLIENT_SECRET=
PDFJS_VERSION_DIST="pdfjs-4.0.379-dist"

VOLC_ACCESSKEY="<MY_DOUBAO_AK>"  
VOLC_SECRETKEY="<MY_DOUBAO_SK>"
ARK_API_KEY="<MY_DOUBAO_API_KEY>"
`

settings.yaml.example:

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  api_base: https://ark.cn-beijing.volces.com/api/v3
  model: ep-20241023141551-9gkxh
  model_supports_json: true # recommended if this is available for your model.
  request_timeout: 1800.0
  max_retries: 3

parallelization:
  stagger: 0.3

async_mode: threaded 

embeddings:
  async_mode: threaded
  llm:
    api_base: https://ark.cn-beijing.volces.com/api/v3
    api_key: ${GRAPHRAG_API_KEY}
    model: ep-20241023145958-t97rc
    type: openai_embedding
    max_retries: 3

chunks:
  size: 512
  overlap: 64
  group_by_columns: [id]

input:
  type: file
  file_type: text 
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file
  base_dir: "cache"

storage:
  type: file 
  base_dir: "output"

reporting:
  type: file
  base_dir: "output"

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 0

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 0

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:

global_search:

### The website screenshot is attached:

chat page (error):
<img width="1470" alt="截屏2024-10-23 下午4 17 49" src="https://github.com/user-attachments/assets/04609efe-6cea-49ed-b1c1-63fc7bd8d4f9">

llm setting page:
<img width="1470" alt="截屏2024-10-23 下午4 18 54" src="https://github.com/user-attachments/assets/486ae700-e13a-4c8c-97ed-ab1aba7c0468">

embedding setting page:
<img width="1470" alt="截屏2024-10-23 下午4 19 27" src="https://github.com/user-attachments/assets/f77734e4-d4f8-4d08-9784-e3bb62662940">

graphRAG construction page(successful):
<img width="1470" alt="截屏2024-10-23 下午4 20 03" src="https://github.com/user-attachments/assets/0251f683-29a1-4ba1-bc4f-955f1c038430">

reasoning setting page:
<img width="1468" alt="截屏2024-10-23 下午4 20 43" src="https://github.com/user-attachments/assets/fd111a00-18d8-48c6-9210-df43f4416960">

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
[2024-10-23T08:09:32Z WARN  lance::dataset] No existing dataset at /home/ws_0802/BYF/kotaemon/ktem_app_data/user_data/files/graphrag/f1ceece8-2bf6-4c78-8156-4464e246d9f0/output/lancedb/entity_description_embeddings.lance, it will be created
Entity count: 6
Error embedding chunk {'OpenAIEmbedding': "Error code: 401 - {'error': {'code': 'AuthenticationError', 'message': 'The API key or AK/SK in the request is missing or invalid. requestId: 021729670972409d262685daafa7b3f3d420ff32e4ca3d4361e53', 'param': '', 'type': 'Unauthorized'}}"}
Traceback (most recent call last):
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 876, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 655, in stream
    docs, infos = self.retrieve(message, history)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 483, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/index/file/graph/pipelines.py", line 366, in run
    context_text, context_records = context_builder.build_context(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/structured_search/local_search/mixed_context.py", line 140, in build_context
    selected_entities = map_query_to_entities(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/context_builder/entity_extraction.py", line 55, in map_query_to_entities
    search_results = text_embedding_vectorstore.similarity_search_by_text(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/vector_stores/lancedb.py", line 118, in similarity_search_by_text
    query_embedding = text_embedder(text)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/context_builder/entity_extraction.py", line 57, in <lambda>
    text_embedder=lambda t: text_embedder.embed(t),
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/llm/oai/embedding.py", line 96, in embed
    chunk_embeddings = np.average(chunk_embeddings, axis=0, weights=chunk_lens)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/numpy/lib/function_base.py", line 550, in average
    raise ZeroDivisionError(
ZeroDivisionError: Weights sum to zero, can't be normalized
Session reasoning type simple
Session LLM doubao
Reasoning class <class 'ktem.reasoning.simple.FullQAPipeline'>
Reasoning state {'app': {'regen': False}, 'pipeline': {}}
Thinking ...
Retrievers [DocumentRetrievalPipeline(DS=<kotaemon.storages.docstores.lancedb.LanceDBDocumentStore object at 0x7fa221b208e0>, FSPath=PosixPath('/home/ws_0802/BYF/kotaemon/ktem_app_data/user_data/files/index_1'), Index=<class 'ktem.index.file.index.IndexTable'>, Source=<class 'ktem.index.file.index.Source'>, VS=<kotaemon.storages.vectorstores.chroma.ChromaVectorStore object at 0x7fa221b20d00>, get_extra_table=False, llm_scorer=LLMTrulensScoring(concurrent=True, normalize=10, prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa217144970>, system_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa217146c20>, top_k=3, user_prompt_template=<kotaemon.llms.prompts.template.PromptTemplate object at 0x7fa2171469e0>), mmr=False, rerankers=[CohereReranking(cohere_api_key='<COHERE_API_KEY>', model_name='rerank-multilingual-v2.0')], retrieval_mode='hybrid', top_k=10, user_id=1), GraphRAGRetrieverPipeline(DS=<theflow.base.unset_ object at 0x7fa3ea5eae60>, FSPath=<theflow.base.unset_ object at 0x7fa3ea5eae60>, Index=<class 'ktem.index.file.index.IndexTable'>, Source=<theflow.base.unset_ object at 0x7fa3ea5eae60>, VS=<theflow.base.unset_ object at 0x7fa3ea5eae60>, file_ids=['c535df11-5de3-4878-bb30-5cd100d08913'], user_id=<theflow.base.unset_ object at 0x7fa3ea5eae60>)]
searching in doc_ids []
[2024-10-23T08:09:43Z WARN  lance::dataset] No existing dataset at /home/ws_0802/BYF/kotaemon/ktem_app_data/user_data/files/graphrag/f1ceece8-2bf6-4c78-8156-4464e246d9f0/output/lancedb/entity_description_embeddings.lance, it will be created
Entity count: 6
Error embedding chunk {'OpenAIEmbedding': "Error code: 401 - {'error': {'code': 'AuthenticationError', 'message': 'The API key or AK/SK in the request is missing or invalid. requestId: 021729670983397d262685daafa7b3f3d420ff32e4ca3d42bd581', 'param': '', 'type': 'Unauthorized'}}"}
Traceback (most recent call last):
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/pages/chat/__init__.py", line 876, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 655, in stream
    docs, infos = self.retrieve(message, history)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/reasoning/simple.py", line 483, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/home/ws_0802/BYF/kotaemon/libs/ktem/ktem/index/file/graph/pipelines.py", line 366, in run
    context_text, context_records = context_builder.build_context(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/structured_search/local_search/mixed_context.py", line 140, in build_context
    selected_entities = map_query_to_entities(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/context_builder/entity_extraction.py", line 55, in map_query_to_entities
    search_results = text_embedding_vectorstore.similarity_search_by_text(
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/vector_stores/lancedb.py", line 118, in similarity_search_by_text
    query_embedding = text_embedder(text)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/context_builder/entity_extraction.py", line 57, in <lambda>
    text_embedder=lambda t: text_embedder.embed(t),
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/graphrag/query/llm/oai/embedding.py", line 96, in embed
    chunk_embeddings = np.average(chunk_embeddings, axis=0, weights=chunk_lens)
  File "/home/ws_0802/anaconda3/envs/kotaemon/lib/python3.10/site-packages/numpy/lib/function_base.py", line 550, in average
    raise ZeroDivisionError(
ZeroDivisionError: Weights sum to zero, can't be normalized
```

### Browsers

Chrome

### OS

Linux

**Comment by atjain02** [comment]
Any update to this? I am having same issue but with Open AI API for chat?

**Comment by elebug** [comment]
Same issue with local ollama setup with Graghrag 0.5.0. Seems like 0.5.0 doesn't support local search method which causes this error

**Comment by taprosoft** [comment]
@elebug Can you try NanoGraphRAG or LightRAG as an alternative to see if it works?
