### ISSUE TITLE
[BUG] The feat “ nano_graphrag” ， i meet the mistake as follow

### ISSUE THREAD

**Issue by WangAo-0** [Cinnamon/kotaemon#440]
### Description

i used ollama as the local llm
llm：qwen2.5
embedding : nomic-embed-text
![image](https://github.com/user-attachments/assets/a28faf06-023f-416f-a0e8-470235bc1e4f)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
❯ python app.py
[nltk_data] Downloading package punkt_tab to /home/oliver/.conda/envs/
[nltk_data]     kotaemon_nano_graphrag/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
GraphRAG dependencies not installed. Try `pip install graphrag future` to install. GraphRAG retriever pipeline will not work properly.
INFO:chromadb.telemetry.product.posthog:Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
Traceback (most recent call last):
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/index/manager.py", line 60, in build_index
    index.on_create()
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/index/file/index.py", line 315, in on_create
    self._setup_resources()
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/index/file/index.py", line 140, in _setup_resources
    self._vs: BaseVectorStore = get_vectorstore(f"index_{self.id}")
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/components.py", line 36, in get_vectorstore
    return deserialize(vs_conf, safe=False)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/theflow/utils/modules.py", line 168, in deserialize
    return cls(**params)
  File "/home/oliver/kotaemon_nano_graphrag/libs/kotaemon/kotaemon/storages/vectorstores/chroma.py", line 43, in __init__
    client = chromadb.PersistentClient(path=path)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/__init__.py", line 153, in PersistentClient
    return ClientCreator(tenant=tenant, database=database, settings=settings)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/api/client.py", line 58, in __init__
    super().__init__(settings=settings)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/api/shared_system_client.py", line 19, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/api/shared_system_client.py", line 30, in _create_system_if_not_exists
    new_system.instance(ServerAPI)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/config.py", line 424, in instance
    impl = type(self)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/api/segment.py", line 125, in __init__
    self._manager = self.require(SegmentManager)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/config.py", line 317, in require
    inst = self._system.instance(type)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/config.py", line 424, in instance
    impl = type(self)
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/segment/impl/manager/local.py", line 96, in __init__
    // PersistentLocalHnswSegment.get_file_handle_count()
  File "/home/oliver/.conda/envs/kotaemon_nano_graphrag/lib/python3.10/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py", line 527, in get_file_handle_count
    hnswlib_count = hnswlib.Index.file_handle_count
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oliver/kotaemon_nano_graphrag/app.py", line 15, in <module>
    app = App()
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/app.py", line 73, in __init__
    self.initialize_indices()
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/app.py", line 84, in initialize_indices
    self.index_manager.on_application_startup()
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/index/manager.py", line 188, in on_application_startup
    self.build_index(**index)
  File "/home/oliver/kotaemon_nano_graphrag/libs/ktem/ktem/index/manager.py", line 68, in build_index
    raise ValueError(f'Cannot create index "{name}": {e}')
ValueError: Cannot create index "File": type object 'hnswlib.Index' has no attribute 'file_handle_count'
```

**Comment by WangAo-0** [comment]
`pip uninstall hnswlib
pip uninstall chroma-hnswlib
pip install chroma-hnswlib
`
it worked

**Comment by WangAo-0** [comment]
```
pip uninstall hnswlib
pip uninstall chroma-hnswlib
pip install chroma-hnswlib
````
it worked after i reinstalled chroma-hnswlib, [references](https://github.com/zylon-ai/private-gpt/issues/1012#issuecomment-2051189357)

**Comment by taprosoft** [comment]
Thanks for the quick feedback we will note it on the README.

**Comment by WangAo-0** [comment]
> Thanks for the quick feedback we will note it on the README.

Btw，the process of creating the nano_graphrag index is so slow that I sometimes wonder if it is stuck. I hope there will be a progress bar to tell the user how the creation is progressing.

**Comment by taprosoft** [comment]
Currently progress is displayed only on the server-side log. Will make a more seamless progress reporting later.

**Comment by WangAo-0** [comment]
The problem has been solved temporarily, but it still needs functional verification. However, it takes too long to create the index, and the prompts to users are not very clear. Even the server-side console is the same. I don’t know when it will be available. When the creation is not completed, the option of available index will appear when the front-end page is refreshed (it is not actually created yet), and an error will be reported again. However, this is a very good feature, and I hope it can be improved as soon as possible. Thanks for integrating this project.

**Comment by chenchen333-dev** [comment]
> ```
> pip uninstall hnswlib
> pip uninstall chroma-hnswlib
> pip install chroma-hnswlib
> ```
> 
> it worked after i reinstalled chroma-hnswlib, [references](https://github.com/zylon-ai/private-gpt/issues/1012#issuecomment-2051189357)

After installing the nano-graphrag dependency package, and at the same time solve the conflict problem, you need to set USE_NANO_GRAPHRAG=true, but adding this variable to the container by export will not take effect, right? If you want to restart the container, you need to stop and delete the original container, and the restarted container does not have nano-graphrag dependencies, but the restart container contains USE_NANO_GRAPHRAG environment variables, can the environment variables be added successfully?
