### ISSUE TITLE
[BUG] The pipeline is running, but the embeddings model is not functioning properly.

### ISSUE THREAD

**Issue by yuqiao9** [Cinnamon/kotaemon#467]
### Description

I am confident that my API has been properly set up, and the pipeline is already in operation, but why do I still receive the following error?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
06:44:52,717 httpx INFO HTTP Request: POST http://192.168.8.101:11434/v1/chat/completions "HTTP/1.1 200 OK"
06:44:52,730 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "Process" with 0 retries took 10.838084932998754. input_tokens=1744, output_tokens=366
06:45:03,9 httpx INFO HTTP Request: POST http://192.168.8.101:11434/v1/chat/completions "HTTP/1.1 200 OK"
06:45:03,13 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "extract-continuation-0" with 0 retries took 10.278559140046127. input_tokens=34, output_tokens=482
06:45:03,22 datashaper.workflow.workflow INFO executing verb merge_graphs
06:45:03,31 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_base_extracted_entities.parquet
06:45:03,282 graphrag.index.run.workflow INFO dependencies for create_summarized_entities: ['create_base_extracted_entities']
06:45:03,283 graphrag.utils.storage INFO read table from storage: create_base_extracted_entities.parquet
06:45:03,288 datashaper.workflow.workflow INFO executing verb summarize_descriptions
06:45:03,291 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_summarized_entities.parquet
06:45:03,517 graphrag.index.run.workflow INFO dependencies for create_base_entity_graph: ['create_summarized_entities']
06:45:03,517 graphrag.utils.storage INFO read table from storage: create_summarized_entities.parquet
06:45:03,522 datashaper.workflow.workflow INFO executing verb cluster_graph
06:45:03,523 graphrag.index.verbs.graph.clustering.cluster_graph WARNING Graph has no nodes
06:45:03,527 datashaper.workflow.workflow ERROR Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/site-packages/graphrag/index/verbs/graph/clustering/cluster_graph.py", line 106, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
06:45:03,530 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "cluster_graph" in create_base_entity_graph: Columns must be same length as key details=None
06:45:03,530 graphrag.index.run.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/graphrag/index/run/run.py", line 227, in run_pipeline
    result = await _process_workflow(
  File "/usr/local/lib/python3.10/site-packages/graphrag/index/run/workflow.py", line 91, in _process_workflow
    result = await workflow.run(context, callbacks)
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/site-packages/graphrag/index/verbs/graph/clustering/cluster_graph.py", line 106, in cluster_graph
    output_df[[level_to, to]] = pd.DataFrame(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
06:45:03,531 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
06:45:03,547 graphrag.index.cli ERROR Errors occurred during the pipeline run, see logs for more details.
```

### Browsers

Microsoft Edge

**Comment by yuqiao9** [comment]
I successfully used Graphrag before, but after reconfiguring, using the same configuration file, it results in the following error.

**Comment by fenzi1223** [comment]
请问已经解决了吗

**Comment by fenzi1223** [comment]
Have you solve this problem?could you please share your solution

**Comment by yuqiao9** [comment]
> 请问已经解决了吗

时间太久了，我得抽空看一下，我记得还是我自己哪边关于graphrag的配置没配置对

**Comment by yuqiao9** [comment]
> 请问已经解决了吗

搞得关于ai的开源太多了，根本一下子想不到
