### ISSUE TITLE
[BUG] GraphRAGIndex missing 'selector' attribute in chat pipeline

### ISSUE THREAD

**Issue by Lee-Ju-Yeong** [Cinnamon/kotaemon#542]
### Description

When attempting to send a message in the chat interface, multiple errors occur due to missing 'selector' attribute in GraphRAGIndex object. This affects the chat pipeline creation and data source persistence.
I want to use the chat functionality without GraphRAGIndex, but these errors are preventing basic chat operations from working.

### Reproduction steps

```bash
1. Set up environment:

conda create -n kotaemon python=3.10
conda activate kotaemon
pip install -e "libs/kotaemon[all]"
pip install -e "libs/ktem"
2.Start application:
python app.py

3. Enter any text in chat input
4. Error appears in console/logs
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Three main errors occur in different functions:

1. In create_pipeline:
AttributeError: 'GraphRAGIndex' object has no attribute 'selector'
2. In check_and_suggest_name_conv:
TypeError: AIMessage.init() missing 1 required positional argument: 'content'
3. In persist_data_source:
AttributeError: 'GraphRAGIndex' object has no attribute 'selector'
```

### Browsers

Chrome

### OS

Windows

### Additional information

Full stack trace attached in comments.

## Additional information
- Python version: 3.10
- Environment: kotaemon conda environment
- Related files: 
  - ktem/pages/chat/__init__.py
  - ktem/reasoning/prompt_optimization/suggest_conversation_name.py
  - kotaemon/base/schema.py

## Expected behavior
The chat pipeline should properly initialize and handle the GraphRAGIndex object with its selector attribute.

**Comment by Lee-Ju-Yeong** [comment]
Traceback (most recent call last):
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "E:\AI\pythonProject\venv\aichat\libs\ktem\ktem\pages\chat\__init__.py", line 832, in chat_fn
    pipeline, reasoning_state = self.create_pipeline(
  File "E:\AI\pythonProject\venv\aichat\libs\ktem\ktem\pages\chat\__init__.py", line 784, in create_pipeline
    if isinstance(index.selector, int):  # 인덱스 선택이 정수일 경우
AttributeError: 'GraphRAGIndex' object has no attribute 'selector'
Traceback (most recent call last):
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
  File "C:\Users\leerj\miniconda3\envs\kotaemon\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\pythonProject\venv\aichat\libs\ktem\ktem\pages\chat\__init__.py", line 673, in persist_data_source
    if index.selector is None:
AttributeError: 'GraphRAGIndex' object has no attribute 'selector'

**Comment by Lee-Ju-Yeong** [comment]
It seems that the code i'm using to customize hiding the GraphRag collection UI on the chat page is causing an error. I would appreciate it if someone could provide a solution on how to hide the GraphRag collection UI on the chat page.
