### ISSUE TITLE
[BUG] GraphRAG doesn't index, fails at create_base_entity_graph

### ISSUE THREAD

**Issue by varunsharma27** [Cinnamon/kotaemon#565]
### Description

Using main-lite Docker image with OpenAI API Key on intro Ui page:
```sh
docker run \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-v /Users/varunsharma/Octostar/apps/app.kotaemon/.env:/app/.env \
-e GRADIO_SERVER_PORT=8080 \
-p 8080:8080 -it --rm \
octostar/app.kotaemon:rag
```

Dockerfile:
```
FROM ghcr.io/cinnamon/kotaemon:main-lite

ENV GRADIO_SERVER_NAME 0.0.0.0
ENV GRADIO_SERVER_PORT 8080
ENV NanoGraphRAG true

RUN pip install nano-graphrag
RUN pip uninstall -y hnswlib chroma-hnswlib && pip install chroma-hnswlib

EXPOSE 8080
```

`.env` file:
```
# settings for OpenAI
OPENAI_API_BASE=https://api.openai.com/v1
OPENAI_API_KEY=my_open_api_key
OPENAI_CHAT_MODEL=gpt-4o
OPENAI_EMBEDDINGS_MODEL=text-embedding-3-small

# settings for Azure OpenAI
# AZURE_OPENAI_ENDPOINT=
# AZURE_OPENAI_API_KEY=
OPENAI_API_VERSION=2024-02-15-preview
AZURE_OPENAI_CHAT_DEPLOYMENT=gpt-35-turbo
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=text-embedding-ada-002

# settings for Cohere
# COHERE_API_KEY=

# settings for local models
LOCAL_MODEL=llama3.1:8b
LOCAL_MODEL_EMBEDDINGS=nomic-embed-text

# settings for GraphRAG
GRAPHRAG_API_KEY=my_open_api_key
GRAPHRAG_LLM_MODEL=gpt-4o-mini
GRAPHRAG_EMBEDDING_MODEL=text-embedding-3-small

# settings for Azure DI
# AZURE_DI_ENDPOINT=
# AZURE_DI_CREDENTIAL=

# settings for Adobe API
# get free credential at https://acrobatservices.adobe.com/dc-integration-creation-app-cdn/main.html?api=pdf-extract-api
# also install pip install "pdfservices-sdk@git+https://github.com/niallcm/pdfservices-python-sdk.git@bump-and-unfreeze-requirements"
# PDF_SERVICES_CLIENT_ID=
# PDF_SERVICES_CLIENT_SECRET=

# settings for PDF.js
PDFJS_VERSION_DIST="pdfjs-4.0.379-dist"
```

Upload Info:

```
Indexing [1/1]: REPORT(KOCG).pdf
 => Converting REPORT(KOCG).pdf to text
 => Converted REPORT(KOCG).pdf to text
 => [REPORT(KOCG).pdf] Processed 2 chunks
 => Finished indexing REPORT(KOCG).pdf
[GraphRAG] Creating index... This can take a long time.
Logging enabled at /app/ktem_app_data/user_data/files/graphrag/4be56183-a8c6-4076-9e2f-4bc9dd7e2b85/output/indexing-engine.log

🚀 create_base_text_units

                                 id  ... n_tokens

0  89fe7c27ea620a375a9b9a115ca4bb0a  ...      320



[1 rows x 5 columns]

🚀 create_base_extracted_entities

                                        entity_graph

0  <graphml xmlns="http://graphml.graphdrawing.or...

🚀 create_summarized_entities

                                        entity_graph

0  <graphml xmlns="http://graphml.graphdrawing.or...

❌ create_base_entity_graph

None

⠋ GraphRAG Indexer 

├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00

├── create_base_text_units

├── create_base_extracted_entities

├── create_summarized_entities

└── create_base_entity_graph❌ Errors occurred during the pipeline run, see logs for more details.

```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
LightRAG dependencies not installed. Try `pip install git+https://github.com/HKUDS/LightRAG.git` to install. LighthRAG retriever pipeline will not work properly.
INFO:chromadb.telemetry.product.posthog:Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
INFO:kotaemon:posthog.capture called with args: ('d126afb8-061c-46b9-b0c7-140c7100b91d', 'ClientStartEvent', {'batch_size': 1, 'in_colab': False, '$process_person_profile': False, 'chroma_version': '0.5.16', 'server_context': 'None', 'hosted': False, 'chroma_api_impl': 'chromadb.api.segment.SegmentAPI', 'is_persistent': False, 'chroma_server_ssl_enabled': False, 'chroma_server_api_default_path': <APIVersion.V2: '/api/v2'>}), kwargs: {}
INFO:kotaemon:posthog.capture called with args: ('d126afb8-061c-46b9-b0c7-140c7100b91d', 'ClientCreateCollectionEvent', {'batch_size': 1, 'collection_uuid': '044a53b6-7bc2-45c9-b2f9-4235e016b804', '$process_person_profile': False, 'chroma_version': '0.5.16', 'server_context': 'None', 'hosted': False, 'chroma_api_impl': 'chromadb.api.segment.SegmentAPI', 'is_persistent': False, 'chroma_server_ssl_enabled': False, 'chroma_server_api_default_path': <APIVersion.V2: '/api/v2'>}), kwargs: {}
INFO:kotaemon:posthog.capture called with args: ('d126afb8-061c-46b9-b0c7-140c7100b91d', 'ClientStartEvent', {'batch_size': 1, 'in_colab': False, '$process_person_profile': False, 'chroma_version': '0.5.16', 'server_context': 'None', 'hosted': False, 'chroma_api_impl': 'chromadb.api.segment.SegmentAPI', 'is_persistent': False, 'chroma_server_ssl_enabled': False, 'chroma_server_api_default_path': <APIVersion.V2: '/api/v2'>}), kwargs: {}
INFO:kotaemon:posthog.capture called with args: ('d126afb8-061c-46b9-b0c7-140c7100b91d', 'ClientCreateCollectionEvent', {'batch_size': 1, 'collection_uuid': 'ad83add5-4eb4-4adf-a5b4-72b3ed39e13f', '$process_person_profile': False, 'chroma_version': '0.5.16', 'server_context': 'None', 'hosted': False, 'chroma_api_impl': 'chromadb.api.segment.SegmentAPI', 'is_persistent': False, 'chroma_server_ssl_enabled': False, 'chroma_server_api_default_path': <APIVersion.V2: '/api/v2'>}), kwargs: {}
INFO:matplotlib.font_manager:generated new fontManager
User "admin" created successfully
Setting up quick upload event
Running on local URL:  http://0.0.0.0:8080
INFO:httpx:HTTP Request: GET http://localhost:8080/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://localhost:8080/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
use_quick_index_mode False
reader_mode default
Chunk size: None, chunk overlap: None
Using reader <kotaemon.loaders.pdf_loader.PDFThumbnailReader object at 0x7effd02305e0>
Page numbers: 1
Got 1 page thumbnails
Adding documents to doc store
[2024-12-13T00:43:21Z WARN  lance::dataset] No existing dataset at /app/ktem_app_data/user_data/docstore/index_2.lance, it will be created
indexing step took 0.7406244277954102
Initializing project at /app/ktem_app_data/user_data/files/graphrag/4be56183-a8c6-4076-9e2f-4bc9dd7e2b85

/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
```

### Browsers

Chrome

### OS

MacOS

**Comment by taprosoft** [comment]
@varunsharma27 GraphRAG requires GRAPHRAG_API_KEY is set (same as OPENAI_API_KEY) https://github.com/Cinnamon/kotaemon#setup-graphrag

If you want to use models managed by Kotaemon, use LightRAG or NanoGraphRAG instead.

**Comment by varunsharma27** [comment]
@taprosoft I have already given up on NanoGraphRAG and LightRAG and none of them worked (too many errors, open issues in the repo).
What worked for me is passing `GRAPHRAG_API_KEY` in the run command itself:
```sh
docker run -v /Users/varunsharma/Octostar/apps/app.kotaemon/.env:/app/.env -e GRAPHRAG_API_KEY=my_openai_key -p 8080:8080 -it octostar/app.kotaemon:rag
```


Apparently the `.env` file isn't checked even though absence of some variables in my `.env` broke the Ui with errors, the final version of the file as posted in the original post is what fixed this:
**`Failed to update model openai: Model openai not found`** upon setting the API key on Welcome screen.

```py
To create a public link, set `share=True` in `launch()`.
User-id: None, can see public conversations: False
User-id: 1, can see public conversations: True
Traceback (most recent call last):
  File "/app/libs/ktem/ktem/llms/manager.py", line 208, in update
    raise ValueError(f"Model {name} not found")
ValueError: Model openai not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/app/libs/ktem/ktem/pages/setup.py", line 228, in update_model
    llms.update(
  File "/app/libs/ktem/ktem/llms/manager.py", line 213, in update
    raise ValueError(f"Failed to update model {name}: {e}")
ValueError: Failed to update model openai: Model openai not found
Traceback (most recent call last):
  File "/app/libs/ktem/ktem/llms/manager.py", line 208, in update
    raise ValueError(f"Model {name} not found")
ValueError: Model openai not found

```


**Error I got for lightrag:**
```py
INFO:lightrag:Load KV full_docs with 1 data
INFO:lightrag:Load KV text_chunks with 1 data
INFO:lightrag:Load KV llm_response_cache with 2 data
INFO:lightrag:Loaded graph from /app/ktem_app_data/user_data/files/lightrag/96166004-a434-4ac7-aa7d-a74a9f75b2a6/input/graph_chunk_entity_relation.graphml with 18 nodes, 6 edges
INFO:nano-vectordb:Load (18, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': '/app/ktem_app_data/user_data/files/lightrag/96166004-a434-4ac7-aa7d-a74a9f75b2a6/input/vdb_entities.json'} 18 data
INFO:nano-vectordb:Load (6, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': '/app/ktem_app_data/user_data/files/lightrag/96166004-a434-4ac7-aa7d-a74a9f75b2a6/input/vdb_relationships.json'} 6 data
INFO:nano-vectordb:Load (1, 3072) data
INFO:nano-vectordb:Init {'embedding_dim': 3072, 'metric': 'cosine', 'storage_file': '/app/ktem_app_data/user_data/files/lightrag/96166004-a434-4ac7-aa7d-a74a9f75b2a6/input/vdb_chunks.json'} 1 data
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/app/libs/ktem/ktem/pages/chat/__init__.py", line 986, in chat_fn
    for response in pipeline.stream(chat_input, conversation_id, chat_history):
  File "/app/libs/ktem/ktem/reasoning/simple.py", line 287, in stream
    docs, infos = self.retrieve(message, history)
  File "/app/libs/ktem/ktem/reasoning/simple.py", line 130, in retrieve
    retriever_docs = retriever_node(text=query)
  File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1097, in __call__
    raise e from None
  File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1088, in __call__
    output = self.fl.exec(func, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/theflow/backends/base.py", line 151, in exec
    return run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 144, in __call__
    raise e from None
  File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 141, in __call__
    _output = self.next_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/theflow/middleware.py", line 117, in __call__
    return self.next_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/theflow/base.py", line 1017, in _runx
    return self.run(*args, **kwargs)
  File "/app/libs/ktem/ktem/index/file/graph/lightrag_pipelines.py", line 382, in run
    entities, relationships, sources = asyncio.run(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/app/libs/ktem/ktem/index/file/graph/lightrag_pipelines.py", line 140, in lightrag_build_local_query_context
    raise ValueError("No results found")
ValueError: No results found
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
```

**Comment by taprosoft** [comment]
@varunsharma27 passing GRAPHRAG_API_KEY in docker run should work. Let me know if you have further issue.
